config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'club3/new'
  get 'giaodien/trangchu'
  get 'giaodien/datsan'
  get 'giaodien/tintuc'
  get 'giaodien/doibong'
  get 'giaodien/lienhe'
  get"dangnhap" => "users#login"
 get"xacnhan/:id" => "lichdau2#xacnhan"
 get"huy/:id" => "lichdau2#huy1"
  post"dangnhap" => "users#login_user"
  get"club2" => "club2#new"
  post"club2" => "club2#create"
  post"/timdoithu/:id/edit" =>"timdoithu#create1"
  delete"logout" => "giaodien#destroy"
  get"taoclub2" => "taoclub2#new"
  resources :theloais , :loaitins, :tintucs  ,:doibongs ,:users , :taoclub1 ,:timdoithu ,:lichdau2


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chucvu.rb
class Chucvu < ApplicationRecord
end

app/models/doibong.rb
class Doibong < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :members
end

app/models/loaitin.rb
class Loaitin < ApplicationRecord
  belongs_to :theloais ,optional: true

  has_many :tintucs
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :doibongs , optional: true
end

app/models/theloai.rb
class Theloai < ApplicationRecord
    has_many :loaitins
end

app/models/tintuc.rb
class Tintuc < ApplicationRecord
  belongs_to :loaitins,optional: true
  mount_uploader :image, ImageUploader
  has_rich_text :content
end

app/models/trandau.rb
class Trandau < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/timdoithu_controller.rb
class TimdoithuController < ApplicationController
  def index
    @doibong = Doibong.all
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
    @trandau = Trandau.all
  end
  def edit
    @doibong1 = Doibong.all
    @doibong = Doibong.find(params[:id])
    @trandau = Trandau.new
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end

  end
  def create1
    @doibong = Doibong.find(params[:id])
    @trandau = Trandau.new
    @trandau.update(trandau_params)

    redirect_to tintucs_path(@trandau)
  end

  private
  def trandau_params
    params.require(:trandau).permit(:id_db1, :id_db2, :id_user2, :id_user, :time ,:ngay ,:confirm)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/club2_helper.rb
module Club2Helper
end

app/helpers/club3_helper.rb
module Club3Helper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/doibong_helper.rb
module DoibongHelper
end

app/helpers/doibongs_helper.rb
module DoibongsHelper
end

app/helpers/giaodien_helper.rb
module GiaodienHelper
end

app/helpers/lichdau2_helper.rb
module Lichdau2Helper
end

app/helpers/lichdau_helper.rb
module LichdauHelper
end

app/helpers/loaitins_helper.rb
module LoaitinsHelper
end

app/helpers/timdoithu_helper.rb
module TimdoithuHelper
end

app/helpers/tintucs_helper.rb
module TintucsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/timdoithu/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Tìm Đồi Thủ</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
	<%= stylesheet_link_tag "tim-db" %>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
	<link rel="shortcut icon" type="image/png" href="img/logo2.png">
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<header style="margin-top: 0;margin-bottom: 10px;">
		<% if @user%>
		<a href="http://localhost/GetPost/assignmentselect/public/home1" class="logo"><img style="width: 87px;height: 60px;margin-left: 60px;margin-top: 13px;" src="http://soccerclub.axiomthemes.com/wp-content/uploads/2016/04/logo.png"></a>
		<div class="menu-toggle"></div>
		<nav>
			<ul>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/home1" style="text-decoration: none;">Trang Chủ</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/tim-san" style="text-decoration: none;">Đặt Sân</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/trangchu/tintuc/tintuc1" style="text-decoration: none;">Tin Tức</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/doibong" style="text-decoration: none;" class="active">Đội Bóng</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/lienhe" style="text-decoration: none;"  >Liên Hệ</a>
				</li>
			</ul>
		</nav>
		<div class="drop-btn" style="cursor: pointer;">
			<div class="drops-btn" style="z-index: 1000;width: 200px;">
				<%= @user.name%>
			</div>
			<div class="wrapper">
				<ul class="menu-bar">
					<li>
			            <a href="http://127.0.0.1:8000/profile">
			              <div class="icon"><span class="fas fa-home"></span></div>
			              Profile
			            </a>
			          </li>
			          <li>
			            <a href="http://127.0.0.1:8000/trangchu/doibong1/profile">
			              <div class="icon"><span class="fas fa-home"></span></div>
			              Club
			            </a>
			          </li>
			          <li>
			            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
			              <div class="icon"><span class="fas fa-home"></span></div>
			              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
		                        @csrf
		                    </form>
			              Đăng Xuất
			            </a>
			          </li>
				</ul>
			</div>
		</div>
		<%else%>
		<a href="#" class="logo"><img style="width: 87px;height: 60px;margin-left: 60px;margin-top: 13px;" src="http://soccerclub.axiomthemes.com/wp-content/uploads/2016/04/logo.png"></a>
		<div class="menu-toggle"></div>
		<nav>
			<ul>
				<li style="padding-right: 5px;">
					<a href="#" style="text-decoration: none;">Trang Chủ</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/tim-san" style="text-decoration: none;">Đặt Sân</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/trangchu/tintuc/tintuc1" style="text-decoration: none;">Tin Tức</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/doibong" style="text-decoration: none;">Đội Bóng</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/lienhe" style="text-decoration: none;" class="active">Liên Hệ</a>
				</li>
			</ul>
		</nav>
		<div class="drop-btn" style="cursor: pointer;">
			<div class="drops-btn" style="z-index: 1000;">
				<a href="http://127.0.0.1:8000/dang-nhap" style="font-size: 12px;text-decoration: none;font-size: 17px;color: white;">Đăng nhập</a>
			</div>
		</div>
		<%end%>
		<div class="side" style="z-index: 3000;">
			<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
			<div id="mySidenav" class="sidenav" style="z-index: 9999;">
				<a href="javascript:void(0)" class="closebtn" onclick="closeNav()" style="background: #fe5900;padding-right: 30px;">&times;</a>
				<div class="side-text">
					<h3>THÔNG TIN NHANH</h3>
					<p>Chất lượng đặt lên hàng đầu <br> nơi giao lưu các đội bóng khác</p>
					<h5><i class="far fa-clock"></i>Thứ Hai - Thứ Sáu: 7 giờ  sáng đến 11h tối <br> Thứ 7 và CN  Full Time</h5>
					<h5><i class="fas fa-map-marker-alt"></i>Đà Nẵng</h5>
					<h5><i class="fas fa-phone-alt"></i>+0829485934234</h5>
					<h5><i class="fas fa-at"></i>nvthang.19it3@gmail.com</h5>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
	</header>
	<%= form_with model: @trandau , url: edit_timdoithu_path,:html => {:multipart => true},  method: :post do |form| %>
		<input type="hidden" name="_token" value="{{csrf_token()}}"/>
		<div class="col-md-10 trandau" style="padding-bottom: 50px;padding-left: 200px;">
			<h1 style="padding-left: 100px;">Chọn địa điểm</h1>
			<div class="form-group" style="display: flex;">
				<%= form.text_field :id_db1 ,value: @doibong.id, placeholder: "Nổi Bật", html: {class: "form-control"}  %>
			</div>
			<div class="form-group" style="display: flex;">
			  <% @doibong1.each do |tl| %>
			  <% if @user.id == tl.id_user%>
				<%= form.text_field :id_db2 ,value: tl.id, placeholder: "Nổi Bật", html: {class: "form-control"}  %>
				<% end %>
				<% end %>
			</div>
			<div class="form-group" style="display: flex;">
				<%= form.text_field :id_user2 ,value: @user.id, placeholder: "Nổi Bật", html: {class: "form-control"}  %>
			</div>
			<div class="form-group" style="display:flex;">
			  <%= form.text_field :id_user ,value: @doibong.id_user, placeholder: "Nổi Bật", html: {class: "form-control"}  %>
			</div>
			<div class="form-group">
				<label>Logo</label>
				<%= image_tag @doibong.image_url.to_s , class: "recipe-show"%>
			</div>
			<div class="form-group">
				<label>Chọn Giờ</label>
				<%= form.select  :time, options_for_select([["17:00", "17:00"], ["18:00", "18:00"],["19:00", "19:00"]]) %>
			</div>
			<div class="form-group">
				<label>Chọn Ngày</label>
				<%= date_select :ngay, start_year: 1800, end_year: Time.now.year %>
			</div>
			<div class="form-group" style="display:none;">
				<%= form.text_field :confirm ,value: "0", placeholder: "Nổi Bật", html: {class: "form-control"}  %>
			</div>
			<%= form.submit "ĐẤU", class: "btn btn-danger"%>
		</div>
	<%end%>
	<div class="banner">
		<%= image_tag 'banner1.jpg' %>
	</div>
	<!-------------------------footer---------------------->
	<footer>
		<div class="container">
			<div class="sec aboutus">
				<h2>About Us</h2>
				<p>Cung cấp cho khách hàng những trận đấu tuyệt vời nhất <br> với chất lượng tốt nhất với các dịch vụ tốt nhất <br> Nơi đặt sự trải nghiệm lên hàng đầu </p>
				<ul class="sci">
					<li>
						<a href="#"><i class="fab fa-facebook"></i></a>
					</li>
					<li>
						<a href="#"><i class="fab fa-instagram"></i></a>
					</li>
					<li>
						<a href="#"><i class="fab fa-twitter"></i></i></a>
					</li>
					<li>
						<a href="#"><i class="fab fa-twitter"></i></i></a>
					</li>	
				</ul>
			</div>
			<div class="sec quickLinks">
				<h2>Quick Links</h2>
				<ul>
					<li><a href="#">Trang Chủ</a></li>
					<li><a href="#">Đặt Sân</a></li>
					<li><a href="#">Liên Hệ</a></li>
					<li><a href="#">Trang Chủ</a></li>
					<li><a href="#">Trang Chủ</a></li>
				</ul>
			</div>
			<div class="sec contact">
				<h2>Contact Info</h2>
				<ul class="info">
					<li>
						<span><i class="far fa-envelope"></i></span>
						<span>678 ldsad sadas ,Đà nẵng <br>Việt Nam</span>
					</li>
					<li>
						<span><i class="far fa-envelope"></i></span>
						<p><a href="#">3218321821738</a><br><a href="#">432432343243</a></p>
					</li>
					<li>
						<span><i class="far fa-envelope"></i></span>
						<span>678 ldsad sadas <br> Đà nẵng <br>Việt Nam</span>
					</li>
				</ul>
			</div>
		</div>
	</footer>
	<div class="copyrightText">
		<p>Copyright @</p>
	</div>
	<script type="text/javascript" src="js/home.js"></script>
	<script type="text/javascript">
    const drop_btn = document.querySelector('.drops-btn');
    const menu_wrapper = document.querySelector('.wrapper');
    drop_btn.onclick = (()=>{
      menu_wrapper.classList.toggle("show");
    });
  </script>
</body>
</html>

app/views/timdoithu/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TÌm Đội Bóng</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag "tim-db" %>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
	<link rel="shortcut icon" type="image/png" href="img/logo2.png">
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<header style="margin-top: 0;margin-bottom: 10px;">
		<% if @user%>
		<a href="http://localhost/GetPost/assignmentselect/public/home1" class="logo"><img style="width: 87px;height: 60px;margin-left: 60px;margin-top: 13px;" src="http://soccerclub.axiomthemes.com/wp-content/uploads/2016/04/logo.png"></a>
		<div class="menu-toggle"></div>
		<nav>
			<ul>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/home1" style="text-decoration: none;">Trang Chủ</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/tim-san" style="text-decoration: none;">Đặt Sân</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/trangchu/tintuc/tintuc1" style="text-decoration: none;">Tin Tức</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/doibong" style="text-decoration: none;" class="active">Đội Bóng</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/lienhe" style="text-decoration: none;"  >Liên Hệ</a>
				</li>
			</ul>
		</nav>
		<div class="drop-btn" style="cursor: pointer;">
			<div class="drops-btn" style="z-index: 1000;width: 200px;">
				<%= @user.name%>
			</div>
			<div class="wrapper">
				<ul class="menu-bar">
					<li>
			            <a href="http://127.0.0.1:8000/profile">
			              <div class="icon"><span class="fas fa-home"></span></div>
			              Profile
			            </a>
			          </li>
			          <li>
			            <a href="http://127.0.0.1:8000/trangchu/doibong1/profile">
			              <div class="icon"><span class="fas fa-home"></span></div>
			              Club
			            </a>
			          </li>
			          <li>
			            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
			              <div class="icon"><span class="fas fa-home"></span></div>
			              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
		                        @csrf
		                    </form>
			              Đăng Xuất
			            </a>
			          </li>
				</ul>
			</div>
		</div>
		<%else%>
		<a href="#" class="logo"><img style="width: 87px;height: 60px;margin-left: 60px;margin-top: 13px;" src="http://soccerclub.axiomthemes.com/wp-content/uploads/2016/04/logo.png"></a>
		<div class="menu-toggle"></div>
		<nav>
			<ul>
				<li style="padding-right: 5px;">
					<a href="#" style="text-decoration: none;">Trang Chủ</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/tim-san" style="text-decoration: none;">Đặt Sân</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/trangchu/tintuc/tintuc1" style="text-decoration: none;">Tin Tức</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/doibong" style="text-decoration: none;">Đội Bóng</a>
				</li>
				<li style="padding-right: 5px;">
					<a href="http://127.0.0.1:8000/lienhe" style="text-decoration: none;" class="active">Liên Hệ</a>
				</li>
			</ul>
		</nav>
		<div class="drop-btn" style="cursor: pointer;">
			<div class="drops-btn" style="z-index: 1000;">
				<a href="http://127.0.0.1:8000/dang-nhap" style="font-size: 12px;text-decoration: none;font-size: 17px;color: white;">Đăng nhập</a>
			</div>
		</div>
		<%end%>
		<div class="side" style="z-index: 3000;">
			<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
			<div id="mySidenav" class="sidenav" style="z-index: 9999;">
				<a href="javascript:void(0)" class="closebtn" onclick="closeNav()" style="background: #fe5900;padding-right: 30px;">&times;</a>
				<div class="side-text">
					<h3>THÔNG TIN NHANH</h3>
					<p>Chất lượng đặt lên hàng đầu <br> nơi giao lưu các đội bóng khác</p>
					<h5><i class="far fa-clock"></i>Thứ Hai - Thứ Sáu: 7 giờ  sáng đến 11h tối <br> Thứ 7 và CN  Full Time</h5>
					<h5><i class="fas fa-map-marker-alt"></i>Đà Nẵng</h5>
					<h5><i class="fas fa-phone-alt"></i>+0829485934234</h5>
					<h5><i class="fas fa-at"></i>nvthang.19it3@gmail.com</h5>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
	</header>
	<form>
	<div class="col-md-10 trandau" style="padding-bottom: 50px;">
	<% @trandau.each do |td|%>
	   <% if td.id_user == @user.id%>
	      <% if td.confirm = 1%>
		  hi
		  <% end %>
		<% else%>
		đấu ngay  
	   <% end %>
	<% end %>
		<% @doibong.each do |tl| %>
		
		<div class="card">
			<div class="card-body">
				<div class="img" style="margin-left: 150px;">
					<td><%= image_tag tl.image_url.to_s , class: "recipe-show1"%></td>
				</div>
				<div class="dia-diem" style="padding-top: 30px;">
					<td><%= tl.tenDoiBong %></td>
				</div>
				<div class="button" >
					<button class="btn2" style="width: 110px;">THÔNG TIN</button>
                    <%if tl.id_user == @user.id%>
					<a href="http://127.0.0.1:8000/tim-doibong2/{{$db->id}}" class="btn1">Club Bạn</a>
                    <%else%>
                    <%= link_to 'Đấu Ngay', edit_timdoithu_path(tl.id), method: 'get', class: "btn1"%>
                    <%end%>
				</div>
			</div>
		</div>
		
		<%end%>
	</div>
	</form>
	<div class="banner">
        <%= image_tag 'banner1.jpg' %>
	</div>
	<!-------------------------footer---------------------->
	<footer>
		<div class="container">
			<div class="sec aboutus">
				<h2>About Us</h2>
				<p>Cung cấp cho khách hàng những trận đấu tuyệt vời nhất <br> với chất lượng tốt nhất với các dịch vụ tốt nhất <br> Nơi đặt sự trải nghiệm lên hàng đầu </p>
				<ul class="sci">
					<li>
						<a href="#"><i class="fab fa-facebook"></i></a>
					</li>
					<li>
						<a href="#"><i class="fab fa-instagram"></i></a>
					</li>
					<li>
						<a href="#"><i class="fab fa-twitter"></i></i></a>
					</li>
					<li>
						<a href="#"><i class="fab fa-twitter"></i></i></a>
					</li>	
				</ul>
			</div>
			<div class="sec quickLinks">
				<h2>Quick Links</h2>
				<ul>
					<li><a href="#">Trang Chủ</a></li>
					<li><a href="#">Đặt Sân</a></li>
					<li><a href="#">Liên Hệ</a></li>
					<li><a href="#">Trang Chủ</a></li>
					<li><a href="#">Trang Chủ</a></li>
				</ul>
			</div>
			<div class="sec contact">
				<h2>Contact Info</h2>
				<ul class="info">
					<li>
						<span><i class="far fa-envelope"></i></span>
						<span>678 ldsad sadas ,Đà nẵng <br>Việt Nam</span>
					</li>
					<li>
						<span><i class="far fa-envelope"></i></span>
						<p><a href="#">3218321821738</a><br><a href="#">432432343243</a></p>
					</li>
					<li>
						<span><i class="far fa-envelope"></i></span>
						<span>678 ldsad sadas <br> Đà nẵng <br>Việt Nam</span>
					</li>
				</ul>
			</div>
		</div>
	</footer>
	<div class="copyrightText">
		<p>Copyright @</p>
	</div>
	<script type="text/javascript" src="js/home.js"></script>
	<script type="text/javascript">
    const drop_btn = document.querySelector('.drops-btn');
    const menu_wrapper = document.querySelector('.wrapper');
    drop_btn.onclick = (()=>{
      menu_wrapper.classList.toggle("show");
    });
  </script>
</body>
</html>